apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-10
  name: busybox-10
spec:
  selector:
    matchLabels:
      workload: busybox-10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-10
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args:
          - wget  https://raw.githubusercontent.com/red-hat-storage/ocs-workloads/io-pattern-busybox/rdr/busybox/scripts/simple_io.sh -O /mnt/test/simple_io.sh;
            chmod +x /mnt/test/simple_io.sh;
            /mnt/test/simple_io.sh
        image: quay.io/ocsci/busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-pvc-10
          readOnly: false
